# Use root/example as user/password credentials
version: '3.8'

services:
  kafka:
    image: apache/kafka:3.7.0
    restart: unless-stopped
    networks:
        - copystagram-net
    hostname: broker
    container_name: broker
    # ports:
    #   - 9092:9092
    #   - 9093:9093
    volumes:
      - ./kafka/config/secrets:/etc/kafka/secrets
      - ./kafka/config/file-input:/mnt/shared/config
      # - ./kafka/data:/tmp/kraft-combined-logs
    environment:
      # Environment variables used by kafka scripts will be needed in case of File input.
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      # Set properties not provided in the file input
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT_HOST://:9092,SSL://:9093,CONTROLLER://:29093,PLAINTEXT://:19092'
      # Override an existing property
      KAFKA_PROCESS_ROLES: 'broker,controller'


  mongo:
    image: mongo:jammy
    restart: always
    networks:
        - copystagram-net
    # ports:
    #   - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234

  kafka-connect:
      image: confluentinc/cp-kafka-connect:7.6.0
      restart: always
      networks:
        - copystagram-net
      # ports:
      #   - 8083:8083
      depends_on:
        - kafka
        - mongo
      environment:
        CONNECT_BOOTSTRAP_SERVERS: broker:19092
        CONNECT_REST_PORT: 8083
        CONNECT_GROUP_ID: "quickstart-avro"
        CONNECT_CONFIG_STORAGE_TOPIC: "quickstart-avro-config"
        CONNECT_OFFSET_STORAGE_TOPIC: "quickstart-avro-offsets"
        CONNECT_STATUS_STORAGE_TOPIC: "quickstart-avro-status"
        CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
        CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
        CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
        CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
        CONNECT_LOG4J_ROOT_LOGLEVEL: WARN
        CONNECT_PLUGIN_PATH: "/usr/share/java,/etc/kafka-connect/jars"
      volumes:
        - ./kafka-connect/jars:/etc/kafka-connect/jars

  copystagram:
    image: copystagram:latest
    container_name: copystagram
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./kafka_2.13-3.7.0:/kafka
    networks:
      - copystagram-net

networks:
  copystagram-net: