# Use root/example as user/password credentials
version: '3.8'

services:
  kafka:
    image: apache/kafka:3.7.0
    restart: unless-stopped
    networks:
        - copystagram-net
    hostname: broker
    container_name: broker
    # ports:
    #   - 9092:9092
    #   - 9093:9093
    volumes:
      - ./kafka/config/secrets:/etc/kafka/secrets
      - ./kafka/config/file-input:/mnt/shared/config
      - ./kafka/data:/tmp/kraft-combined-logs
      - ./logs:/copystagram/logs
    environment:
      # Environment variables used by kafka scripts will be needed in case of File input.
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      # Set properties not provided in the file input
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT_HOST://:9092,SSL://:9093,CONTROLLER://:29093,PLAINTEXT://:19092'
      # Override an existing property
      KAFKA_PROCESS_ROLES: 'broker,controller'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 1G


  kafka-connect:
      image: confluentinc/cp-kafka-connect:7.6.0
      restart: always
      hostname: kafka-connect
      container_name: kafka-connect
      networks:
        - copystagram-net
      ports:
        - 8083:8083
      depends_on:
        - kafka
      environment:
        CONNECT_BOOTSTRAP_SERVERS: broker:9092
        CONNECT_REST_PORT: 8083
        CONNECT_GROUP_ID: "quickstart-avro"
        CONNECT_CONFIG_STORAGE_TOPIC: "quickstart-avro-config"
        CONNECT_OFFSET_STORAGE_TOPIC: "quickstart-avro-offsets"
        CONNECT_STATUS_STORAGE_TOPIC: "quickstart-avro-status"
        CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
        CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
        CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
        CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
        CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
        CONNECT_PLUGIN_PATH: "/usr/share/java,/etc/kafka-connect/jars"
      volumes:
        - ./kafka-connect/jars:/etc/kafka-connect/jars
      deploy:
        resources:
          limits:
            cpus: '0.3'
            memory: 1.5G

  copystagram:
    image: copystagram:latest
    container_name: copystagram
    ports:
      - 80:80
      - 443:443
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - ./kafka_2.13-3.7.0:/kafka
      - /etc/letsencrypt/live/your-service-domain/fullchain.pem:/etc/ssl/live/fullchain1.pem
      - /etc/letsencrypt/live/your-service-domain/privkey.pem:/etc/ssl/live/privkey1.pem
      - ./static:/copystagram/copystagram-backend/copystagram/src/main/resources/static
    networks:
      - copystagram-net

networks:
  copystagram-net:

configs:
  nginx-config:
    file: "./nginx.conf"
